# Generated by Django 2.0.5 on 2019-11-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(default='', max_length=128),
        ),
    ]
