# Generated by Django 2.0.5 on 2019-11-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191119_0332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
